fix: incompatible ruby:3.0 with rubygems-update-3.6.9
docker build . -t systopia-website

 => ERROR [2/9] RUN gem update --system                                                                                                                                                                          2.3s
------
 > [2/9] RUN gem update --system:
1.996 ERROR:  Error installing rubygems-update:
1.996   rubygems-update-3.6.9 requires Ruby version >= 3.1.0. The current ruby version is 3.0.7.220.
1.997 ERROR:  While executing gem ... (NoMethodError)
1.997     undefined method `version' for nil:NilClass
2.018 Updating rubygems-update
------
Dockerfile:5
--------------------
   3 |
   4 |     # Update gem so that it can still build
   5 | >>> RUN gem update --system
   6 |
   7 |     # Install ruby dependencies necessary to build and serve website
--------------------
ERROR: failed to solve: process "/bin/sh -c gem update --system" did not complete successfully: exit code: 1